[build]
  command = "ng build --configuration=production"
  publish = "dist/nanotrejoweb/browser"
  base = "."

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200